services:
  frontend:
    container_name: frontend-app
    build: ./frontend
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src/:/app/src/
    depends_on:
      - backend
  backend:
    container_name: backend-app
    build: ./backend
    env_file:
      - backend/.env
    ports:
      - "3310:3310"
    volumes:
      - ./backend/src/:/app/src/
    depends_on:
      - database
  database:
    container_name: postgres-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_HOST=${DB_HOST}
    volumes:
      - ./database/:/var/lib/postgresql/data
