services:
  database:
    container_name: postgres-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD="toto"
      - POSTGRES_DB="toto"
      - POSTGRES_USER="toto"
      - POSTGRES_HOST="database"
    volumes:
      - ./database/:/var/lib/postgresql/data
  backend:
    container_name: backend-app
    build: ./backend
    env_file:
      - backend/.env
    ports:
      - "3310:3310"
    volumes:
      - ./backend/src/:/app/src/
    depends_on:
      - database
  frontend:
    container_name: frontend-app
    build: ./frontend
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src/:/app/src/
    depends_on:
      - backend
