GET http://localhost:3310/tags

###

POST http://localhost:3310/tags
Content-Type: application/json

{
    "nom": "moi"
}

###

PUT http://localhost:3310/tags/1
Content-Type: application/json

{
    "nom": "hello"
}

###

DELETE http://localhost:3310/tags/1